### ISSUE TITLE
Bug ordre affichage de la ligne Total dans tri_a_plat

### ISSUE THREAD

**Issue by leomignot** [emilienschultz/pyshs-bib#10]
La ligne Total présente un bug d'ordre d'affichage dans tri_a_plat : elle ne s'affiche pas en fin de tableau mais au "milieu" si des modalités de réponse arrivent après dans l'ordre alphabétique (u/v/w).
Lié à un tri par ordre alphabétique dans les modalités d'affichage ?

**Comment by emilienschultz** [comment]
Effectivement, j'ai changé en ajoutant le total une fois le tableau ordonné.
