### ISSUE TITLE
regression_logistique et SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by leomignot** [emilienschultz/pyshs-bib#13]
regression_logistique revoie une erreur si un nom de variable (intitulé des colonnes d'un jeu de données) contient un espace.

Corriger ou ajouter un avertissement ?

**Comment by emilienschultz** [comment]
ouvre une issue

Le lun. 15 nov. 2021 à 15:46, Léo Mignot ***@***.***> a
écrit :

**Comment by emilienschultz** [comment]
Done
