### ISSUE TITLE
restructurer correctement la bibliothèque dans un dossier pyshs

### ISSUE THREAD

**Issue by emilienschultz** [emilienschultz/pyshs-bib#28]
Créer un dossier pyshs pour les scripts et test pour les tests
+ est-ce qu'il y a quelque chose à modifier pour que cela fonctionne @Carreau  (avec flit + la publication de la biblio) ?

**Comment by emilienschultz** [comment]
@Carreau perfect. question : do the tests need to be on a specific folder "test" ? Or at the root of the librairy ?

**Comment by Carreau** [comment]
As you wish, a test subfolder may help with growth.
