### ISSUE TITLE
Pourcentages dans pyshs.tableau_croise_multiple

### ISSUE THREAD

**Issue by leomignot** [emilienschultz/pyshs-bib#7]
Il me semble que pyshs.tableau_croise_multiple présente à la fois des pourcentages en ligne (pour les modalités) et en colonne (pour la colonne total). Est-ce un choix afin de présenter plus d'informations ?

**Comment by emilienschultz** [comment]
Bonne remarque. J'ai simplifié pour le moment en ne faisant que par ligne (sans complexifier la lecture du tableau), je verrai pour rajouter ultérieurement une colonne tri à plat en plus.
Et j'ai rajouté le total.
