### ISSUE TITLE
TypeError dans tri_a_plat

### ISSUE THREAD

**Issue by leomignot** [emilienschultz/pyshs-bib#9]
tri_a_plat renvoie une Type Error pour les variables de type float,  int et bool

TypeError: '<' not supported between instances of 'str' and 'float'
TypeError: '<' not supported between instances of 'str' and 'int'
TypeError: '<' not supported between instances of 'str' and 'bool'

L'erreur ne se produit pas avec les mêmes variables dans tableau_croise.

**Comment by emilienschultz** [comment]
Effectivement, corrigé en forçant la mise sous forme string de l'index.
